version: '3.8'
services:
    app:
        build: .
        ports:
            - "${PORT}:3000"
        environment:
            DATABASE_URL: ${DATABASE_URL}
        depends_on:
            - db
    db:
        container_name: postgres
        image: postgres:13
        ports:
            - "${POSTGRES_PORT}:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
